### ISSUE TITLE
在win10系统上，并不能正常使用FastCopy的复制、粘贴和删除

### ISSUE THREAD

**Issue by JuLongZhiLu** [HO-COOH/FastCopy#11]
在win10系统上，并不能正常使用FastCopy的复制、粘贴和删除
点击复制、粘贴没有效果
此外，无法点击删除

**Comment by HO-COOH** [comment]
Fixed in #[a279f3f](https://github.com/HO-COOH/FastCopy/commit/a279f3fc920a65694718bf6ece260326de20e4e1)
